<a href="https://colab.research.google.com/github/22zunaid/Data-science/blob/master/KNNandK-means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier

pd.set_option("max_columns", None)

In [ ]:
data=load_wine()
X=pd.DataFrame(data['data'], columns=data['feature_names'])
y=data['target']

print(X)

In [6]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [7]:
X.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64

In [8]:
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size=0.2,random_state=42)

In [9]:
scaler =MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [10]:
print(X_train_scaled)

[[0.87105263 0.16089613 0.71657754 ... 0.07317073 0.25274725 0.30102443]
 [0.39473684 0.94093686 0.68449198 ... 0.27642276 0.15384615 0.18676123]
 [0.35263158 0.03665988 0.39572193 ... 0.45528455 0.54945055 0.30102443]
 ...
 [0.88157895 0.19959267 0.54545455 ... 0.58536585 0.63369963 1.        ]
 [0.43684211 0.13034623 0.48128342 ... 0.3902439  0.28937729 0.17100079]
 [0.34473684 0.31771894 0.58823529 ... 0.2601626  0.77289377 0.12608353]]


In [11]:
model=KNeighborsClassifier(n_neighbors=5)
model.fit(X_train_scaled, y_train)



KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [12]:
y_pred = model.predict(X_test_scaled)

In [13]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.9444444444444444

K-Means

In [14]:
data = load_wine()

X = data['data']


In [17]:
scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X)


In [18]:
from sklearn.cluster import KMeans

In [19]:
model = KMeans(n_clusters=2, random_state=42)

In [20]:
model.fit(X_scaled)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=42, tol=0.0001, verbose=0)

In [24]:
y_pred = model.labels_

In [25]:
print(y_pred)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 1 1 1 0 1 0 1 1 1
 1 0 1 0 1 1 1 1 1 0 1 1 0 1 0 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1
 1 0 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
